<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MyriadOfDragons.CloudCode.PermitWeekKey</RootNamespace>
    <AssemblyName>PermitWeekKey</AssemblyName>
    <IsPackable>true</IsPackable>
    <IsPublishable>true</IsPublishable>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Com.Unity.Services.CloudCode.Core" Version="0.0.5" />
    <PackageReference Include="Com.Unity.Services.CloudCode.Apis" Version="0.0.26" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="PermitWeekKey.ServerTests\**" />
    <EmbeddedResource Remove="PermitWeekKey.ServerTests\**" />
    <None Remove="PermitWeekKey.ServerTests\**" />
  </ItemGroup>
</Project>
